### ISSUE TITLE
Create initial (tier 1) community data tables

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/StanC#1]
@maggiesu0725 I've created a new issue for producing the initial data tables from the tier 1 list for The Commons. 

[List of tier 1 data](https://urbanorg.box.com/s/lkyjyetpvamxagd8dh7pwjal21y5k241)

Tables will resemble [those prepared for BridgePk](https://urbanorg.box.com/s/ynkkm8921fcddwks3ljozu0gxds63eky). 

See [BPKPresentationResults.sas](https://github.com/NeighborhoodInfoDC/BridgePk/blob/master/Prog/BPKPresentationResults.sas) program for how those data were compiled. 

Comparisons (columns) for The Commons tables will be:
- Commons catchment area (geo=_stantoncommons_)
- Ward 8
- DC

There may be a need to create issues in other repos to produce the summary files needed for the Commons geography. 

Need to deliver this work by June 15. Would like to see it a week before so that we can make any changes. Please let me know if you have any questions.

Project no: 101662-0001-001

cc: @rpitingolo

**Comment by ptatian** [comment]
Additions to tier 1 data based on phone call with Commons.
- Rent burdens [ACS: paying over 30% or 50% income on rent]
- Housing turnover [ACS: moved homes in the past year]
- Assisted housing units from Catalog [Preservation Catalog, see Bridge Park table program for data source]

Info/source for 500 Cities census tract level health data: 
- https://www.cdc.gov/500cities/
- https://chronicdata.cdc.gov/browse?category=500+Cities

**Comment by rpitingolo** [comment]
@ptatian we've read in the data and saved the base file here: L:\Libraries\CDC500\Data

I'm stuck on how to create the summary files from this. Is %Create_all_summary_from_tracts the correct macro to use? And relatedly is there instructions anywhere on how to define the parameters? cc: @maggiesu0725
