### ISSUE TITLE
Revise Commons tier 1 data tables

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/StanC#3]
Make revisions to tier 1 data tables based on feedback from The Commons. Main feedback was to make sure the tables are clear and self-explanatory to someone who doesn't know data or the specific data sources well. 

**Before starting this issue, please merge pull request #2 and close issue #1. Sync L: repo. Fetch and pull updated master to local repository and create a new branch.**

**I made some formatting changes to the Excel workbook. You should use the current version that is in L:\Libraries\StanC\Data.**

### General
- [x] Do a spell check to remove misspellings
- [x] Be consistent with table title, row and column label capitalization
- [x] Be consistent with how ages are described. In some places we say "age XX," others we say "XX years old." Let's go with "years old."
- [x] Use comma (,) as thousands separator
- [x] Make sure all proportions are correctly formatted as percentages, not decimals (ie, 44%, not 0.44). 
- [x] Where necessary, add notes below the table source to explain data definitions and aid with interpretation (eg, explain what "gross rent," "cost burden," "severe cost burden," etc. mean).
- [x] Put total table population/households/housing units as the first row (specific tables noted below)
- [x] Add percentages to tables. For certain tables, I would do this by adding a parallel set of columns to the tables with just counts. For instance, in the population table, add three columns for Stanton Commons, Ward 8, and all DC to the right of the current columns and show the percentages of the total population in the different groups for each area. (Total row will be 100%.) But there are other tables for which this won't be the right approach. See below for specific guidance for each table. 

### Reorganize
- [x] Put summary tables up front, more detailed in an "appendix" and re-order tables so that they better align with the four goals 
  - Demographics
    - Population counts
    - Households by type
    - Educational Attainment
  - Goal #1 - Children milestones
    - Early Development Instrument (EDI)
  - Goal #2 - Families housing/food
    - Share of People Below the Federal Poverty Level
    - Employment Characteristics (new Labor force + Employment tables, see below)
    - Employment by Major Civilian Occupations
    - Employment by Annual Earnings
    - Renter and owner households
    - Housing Cost Burden
    - Household Using Housing Choice Vouchers
  - Goal #3 - Families emotional
    - Family Emotional Well-being
    - Death by Cause
  - Goal #4 - Babies
    - Health Insurance Coverage by Age
    - Birth by Type
  - Appendix: Detailed tables
    - Renter Occupied Units by gross rent level
    - Annual Births
    - Annual Births with Adequate Prenatal Care
    - Annual Womens Having First Prenatal Visit in 1st Trimester
    - Annual low and very low birth weight babies
    - Annual Pre-term births
    - Annual Deaths
    - Annual Deaths to persons 15-19
    - Deaths to adults 18+ years old
    - Annual Accidental Deaths, Annual Deaths from Cancer, ... etc.
    - Property Crimes
    - Violent Crimes
    - Annual TANF caseload
    - Annual SNAP caseload

### Population and Household Counts
- [x] Show only counts of people in first three columns and then percentages in three (new) columns. 
- [x] No household data in this table so remove "and household" from title.
- [x] Use these age categories: 
  - Under 5 years old
  - 5-17 years old
  - Under 18 years old
  - 18-34 years old
  - 35-64 years old
  - 65 years and older
- [x] Put more separation between different sub-groups within a table, such as with a line or more space (eg, between male/female and age categories)

### Households by Type
- [x] Add total households row at top of table
- [x] Show only counts of households in first three columns and then percentages in three (new) columns. 
- [x] Confirm whether these groups add up to total households (they should)
- [x] Female householder row label not fully visible
- [x] Add table note to explain difference between family and nonfamily households, any other household types that might not be clear from labels alone. 

### Renter and owner households
- [x] Add total households row at top of table
- [x] Show only counts in first three columns and then percentages in three (new) columns. 
- [x] Title says "households," but table rows "occupied units." They are the same but it could be confusing for people who don't know that. I would just call them households. 

### Renter Occupied Units by gross rent level
- [x] Change "occupied units" to "households" in title
- [x] Add total renter households row at top of table
- [x] Show only counts in first three columns and then percentages in three (new) columns. 
- [x] I would condense this by using groups of $100 up until $1,000 (ie, Less than $100, $100 to $199, $200 to $299, etc.)
- [x] Add a table note to define "gross rent."

### Housing Cost Burden
- [x] Put more separation between owner and renter groups within table, such as with a line or more space
- [x] Add total renter households with cost burden calculated and total owner households with cost burden calculated rows to this table. 
- [x] People had difficulty understanding what "share" meant in this table. Following my general advice, remove the share rows from this table and replace them with percentage columns. 
- [x] Add a table note to explain cost burden definitions.

### Educational Attainment
- [x] Show only counts of people in first three columns and then percentages in three (new) columns. 
- [x] People found the data in this table hard to understand. Suggest we change the rows to the following.
  - Total population 25 years and older 
  - Without a high school diploma or equivalent
  - High school diploma/equivalent, no college [Note: The numbers labeled, "Only a High School Degree or Equivalent," don't look correct in the current table. They seem to include everyone who has _at least_ completed high school, as well as went to college.]
  - Some college
  - Bachelors or graduate/prof degree

### Share of People Below the Federal Poverty Level
- [x] Show only counts of people in first three columns and then percentages in three (new) columns. This will mean adding "Persons below poverty" as a new row.

### Employment Characteristics
- [x] People didn't understand the distinction between being in the labor force and being employed. Suggest we divide this into two tables - one for labor force participation and one for employment. **Labor force participation table** would have these rows.
  - Total population 16 years and older
  - Persons in labor force

**Employment table** would have these rows.
  - Total population 16 years and older in the labor force
  - Employed persons
  - Unemployed persons
  - [x] Add notes explaining terms "labor force," "employed," and "unemployed." 
- [x] Show only counts in first three columns and then percentages in three (new) columns. 

### Employment by Major Civilian Occupations
- [x] Show only counts in first three columns and then percentages in three (new) columns. 
- [x] Reorder table rows so that they are in descending order by the number of persons in Stanton Commons in each occupation type. 

### Employment by Annual Earnings
- [x] Add total row at top of table
- [x] Show only counts in first three columns and then percentages in three (new) columns. 

### Health Insurance Coverage by Age
- [x] Add total pop rows to both parts of this table
- [x] Instead of the way I said in the other tables, let's make the percentage columns the % of persons by age group with/without insurance. So, for under 18 years old, % with insurance + % without insurance = 100%, etc. 

### Annual births, etc.
- For all of the birth tables, we don't need to add total rows or percentages.  
- [x] Add notes to explain definitions of prenatal care, etc. 

### Annual deaths, etc. 
- For all of the death tables, don't need to add total rows or percentages.
- [x] Annual deaths table should be with the other death tables. 

### Crimes
- Don't need to add total rows or precentages
- [x] Add note explaining violent and property crime definitions

### TANF, SNAP
- Don't need to add total rows or percentages

### Birth by type, Death by cause, HHs with vouchers, family emotional well being, EDI
- Don't need to add total rows or percentages

**Comment by maggiesu0725** [comment]
@ptatian  the tables are updated in this new spreadsheet I created (had to reorganize a lot of tables and it is easier to start a new file), L:\Libraries\StanC\Data\Stanton Commons Baseline Data Tabulation 07-10-2018.xlsx

**Comment by ptatian** [comment]
Thank you, @maggiesu0725. I'll take a look now.

**Comment by ptatian** [comment]
@maggiesu0725 Would you please create a pull request for this? Thank you.
